In [1]:
import numpy as np

##### 创建矩阵 np.array([[column1[,[column2]])

In [2]:
arr = np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


##### 矩阵的行列数 name.shape
##### 矩阵的维数 name.ndim
##### 矩阵的元素个数 name.size

In [3]:
print('shape:',arr.shape)
print('number of dim:',arr.ndim)
print('size:',arr.size)

shape: (2, 3)
number of dim: 2
size: 6


###### 全是0的矩阵 np.zeros(())
###### 全是1的矩阵 np.ones(())
###### 随机生成矩阵 np.random.random(())

In [4]:
a = np.zeros((2,3))
print("a:",a)

b = np.ones((3,2))
print("b:",b)

c = np.random.random((3,3))
print("c:",c)

a: [[0. 0. 0.]
 [0. 0. 0.]]
b: [[1. 1.]
 [1. 1.]
 [1. 1.]]
c: [[0.90437362 0.95854747 0.11054865]
 [0.4462528  0.30796783 0.7038579 ]
 [0.99767887 0.86530776 0.16080183]]


###### 根据数值范围生成矩阵 np.arange(min,max,step).reshape((r,c))  默认下限为0 步长为1
###### 根据元素个数生成矩阵 np.linspace(num1,numx,n).reshape((r,c))

In [5]:
d = np.arange(1,5,0.5).reshape((2,4))
print("d:",d)

e = np.linspace(1,99,6).reshape((3,2))
print("e:",e)

d: [[1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5]]
e: [[ 1.  20.6]
 [40.2 59.8]
 [79.4 99. ]]


###### 矩阵对应位置直接相乘 a*b

In [6]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[3,4,5],[1,2,3]])
c = a*b
print(c)

[[ 3  8 15]
 [ 2  6 12]]


###### 矩阵相乘 np.dot(a,b)

In [7]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[3,4],[1,2],[2,3]])
c = np.dot(a,b)
print("a:",a)
print("b:",b)
print("c:",c)

a: [[1 2 3]
 [2 3 4]]
b: [[3 4]
 [1 2]
 [2 3]]
c: [[11 17]
 [17 26]]


###### 判断矩阵中元素大小

In [8]:
b = 2
print(b<3)

True


###### 求和、最大值、最小值、均值、累加值 np.sum max min mean cumsum
axis=0 对列做运算

In [9]:
a=np.array([[1,2,3],[2,3,4]])
print("sum:",np.sum(a,axis=0))
print("max：",np.max(a,axis=0))
print("min：",np.min(a,axis=0))
print("mean：",np.mean(a,axis=1))
print("cumsum：",np.cumsum(a,axis=1))

sum: [3 5 7]
max： [2 3 4]
min： [1 2 3]
mean： [2. 3.]
cumsum： [[1 3 6]
 [2 5 9]]


###### 求最大值最小值在第几位 np.argmax
位数从0开始

In [10]:
a=np.array([[1,2,3],[2,3,4]])
print(np.argmax(a,axis=0))

[1 1 1]


###### 计算累差值 np.diff

In [11]:
a=np.array([[1,5,6],[3,7,5]])
print(np.diff(a,axis=0))

[[ 2  2 -1]]


###### 得出哪些行和列的值非零 np.nonzero()
给出的结果中为非零值所在的行和列的位置 第一部分为行 第二部分为列

In [12]:
a=np.array([[1,0,6],[3,7,5]])
print(a)
print(np.nonzero(a))

[[1 0 6]
 [3 7 5]]
(array([0, 0, 1, 1, 1], dtype=int64), array([0, 2, 0, 1, 2], dtype=int64))


解释：一行一列、一行三列、二行一列、二行二列、二行三列

###### 逐行数字排序

In [13]:
a=np.array([[1,0,6],[3,7,5]])
print(np.sort(a,axis=1))

[[0 1 6]
 [3 5 7]]


###### 转置 np.transpose()

In [14]:
a=np.array([[1,0,6],[3,7,5]])
print("a_:",np.transpose(a))

a_: [[1 3]
 [0 7]
 [6 5]]


###### 数据平滑 np.clip(a,min,max)

In [15]:
a=np.array([[151,0,6],[3,7,0.05]])
print(np.clip(a,1,10))

[[10.  1.  6.]
 [ 3.  7.  1.]]


###### 根据位置找到具体某个值  name[position,position]
从0开始
：代表所有数
###### 非传递赋值

In [16]:
a=np.array([[1,0,6],[3,7,5]])
print(a[1,1])

b = a.copy()
a[1,1]=18 #根据位置改变某一个值
print(a)
print(b)

7
[[ 1  0  6]
 [ 3 18  5]]
[[1 0 6]
 [3 7 5]]


###### 输出所有行/列 row column
###### 转置后输出
###### 输出所有元素

In [17]:
a=np.array([[1,0,6],[3,7,5]])
for row in a:
    print(row)
for column in a.T:
    print(column)
for item in a.flat:
    print(item)

[1 0 6]
[3 7 5]
[1 3]
[0 7]
[6 5]
1
0
6
3
7
5


In [18]:
a=np.array([[1,0,6],[3,7,5]])
b=np.array([[3,4,7],[2,8,4]])
print(a)
print(b)

[[1 0 6]
 [3 7 5]]
[[3 4 7]
 [2 8 4]]


###### 上下合并矩阵

In [19]:
print(np.vstack((a,b)))

[[1 0 6]
 [3 7 5]
 [3 4 7]
 [2 8 4]]


###### 左右合并矩阵

In [20]:
print(np.hstack((a,b)))

[[1 0 6 3 4 7]
 [3 7 5 2 8 4]]


###### 分割矩阵  np.split(a,分割为几块,对行/列分) 
1为竖向分割 0为衡量分割

In [21]:
print(np.split(b,3,1))

[array([[3],
       [2]]), array([[4],
       [8]]), array([[7],
       [4]])]


###### 不等分割矩阵 np.array_split(name,块数，行/列）
第一个矩阵最多

In [22]:
print(np.array_split(b,2,1))

[array([[3, 4],
       [2, 8]]), array([[7],
       [4]])]


###### 横向分割矩阵 np.vsplit(name,num)

In [23]:
print(np.vsplit(a,2))

[array([[1, 0, 6]]), array([[3, 7, 5]])]


###### 纵向分割矩阵 np.hsplit(name,num)

In [24]:
print(np.hsplit(a,3))

[array([[1],
       [3]]), array([[0],
       [7]]), array([[6],
       [5]])]
