In [1]:
import numpy as np

In [2]:
#创建矩阵 np.array([[column1],[column2]])
arr = np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


In [3]:
#矩阵的行列数 namex.shape
print('shape:',arr.shape)
#矩阵的维数 namex.ndim
print('number of dim:',arr.ndim)
#矩阵的元素个数 namex.size
print('size:',arr.size)

shape: (2, 3)
number of dim: 2
size: 6


In [4]:
#全是0的矩阵
a = np.zeros((2,3))
print("a:",a)
#全是1的矩阵
b = np.ones((3,2))
print("b:",b)
#随机生成矩阵
c = np.random.random((3,3))
print("c:",c)

a: [[0. 0. 0.]
 [0. 0. 0.]]
b: [[1. 1.]
 [1. 1.]
 [1. 1.]]
c: [[0.55848856 0.50852519 0.45616956]
 [0.71807243 0.29272935 0.20704363]
 [0.20614456 0.63367445 0.59771044]]


In [5]:
#根据数值范围生成矩阵 np.arange(min,max,step).reshape((r,c))  默认下限为0 步长为1
d = np.arange(1,5,0.5).reshape((2,4))
print("d:",d)
#根据元素个数生成矩阵 np.linspace(num1,numx,n).reshape((r,c))
e = np.linspace(1,99,6).reshape((3,2))
print("e:",e)

d: [[1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5]]
e: [[ 1.  20.6]
 [40.2 59.8]
 [79.4 99. ]]


In [6]:
#矩阵对应位置直接相乘
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[3,4,5],[1,2,3]])
c = a*b
print(c)

[[ 3  8 15]
 [ 2  6 12]]


In [7]:
#矩阵相乘
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[3,4],[1,2],[2,3]])
c = np.dot(a,b)
print("a:",a)
print("b:",b)
print("c:",c)

a: [[1 2 3]
 [2 3 4]]
b: [[3 4]
 [1 2]
 [2 3]]
c: [[11 17]
 [17 26]]


In [8]:
#判断矩阵中元素大小
b = 2
print(b<3)

True


In [9]:
a=np.array([[1,2,3],[2,3,4]])
#axis 1代表行 0代表列
#求和
print("sum:",np.sum(a,axis=0))
#最大值
print("max：",np.max(a,axis=0))
#最小值
print("min：",np.min(a,axis=0))
#均值
print("mean：",np.mean(a,axis=1))
#累加值
print("cumsum：",np.cumsum(a,axis=1))

sum: [3 5 7]
max： [2 3 4]
min： [1 2 3]
mean： [2. 3.]
cumsum： [[1 3 6]
 [2 5 9]]


In [10]:
a=np.array([[1,2,3],[2,3,4]])
#求最大值最小值在第几位 位数从0开始
print(np.argmax(a,axis=0))

[1 1 1]


In [11]:
a=np.array([[1,5,6],[3,7,5]])
#计算每一行的累差值
print(np.diff(a,axis=0))

[[ 2  2 -1]]


In [12]:
a=np.array([[1,0,6],[3,7,5]])
#得出哪些行和列的值非零
print(np.nonzero(a))
#给出的结果中为非零值所在的行和列的位置 第一部分为行 第二部分为列

(array([0, 0, 1, 1, 1], dtype=int64), array([0, 2, 0, 1, 2], dtype=int64))


In [13]:
a=np.array([[1,0,6],[3,7,5]])
#逐行数字排序
print(np.sort(a,axis=1))

[[0 1 6]
 [3 5 7]]


In [14]:
a=np.array([[1,0,6],[3,7,5]])
#转置
print("a_:",np.transpose(a))

a_: [[1 3]
 [0 7]
 [6 5]]


In [15]:
a=np.array([[151,0,6],[3,7,0.05]])
#数据平滑 np.clip(a,min,max)
print(np.clip(a,1,10))

[[10.  1.  6.]
 [ 3.  7.  1.]]


In [16]:
a=np.array([[1,0,6],[3,7,5]])
#根据位置找到具体某个值 0开始 ：代表所有数
print(a[1,1])
#非传递赋值
b = a.copy()
a[1,1]=18 #根据位置改变某一个值
print(a)
print(b)

7
[[ 1  0  6]
 [ 3 18  5]]
[[1 0 6]
 [3 7 5]]


In [17]:
a=np.array([[1,0,6],[3,7,5]])
#输出所有行/列 row column
for row in a:
    print(row)
#转置后输出
for column in a.T:
    print(column)
#输出所有元素
for item in a.flat:
    print(item)

[1 0 6]
[3 7 5]
[1 3]
[0 7]
[6 5]
1
0
6
3
7
5


In [18]:
a=np.array([[1,0,6],[3,7,5]])
b=np.array([[3,4,7],[2,8,4]])
#上下合并矩阵
print(np.vstack((a,b)))
#左右合并矩阵
print(np.hstack((a,b)))
print("------------")
#分割矩阵  np.split(a,分割为几块,对行/列分) 1为竖向分割 0为衡量分割
print(np.split(b,3,1))
print("------------")
#不等分割矩阵 第一个矩阵最多
print(np.array_split(b,2,1))
print("------------")
#横向分割矩阵
print(np.vsplit(a,2))
print("------------")
#竖向分割矩阵
print(np.hsplit(a,3))

[[1 0 6]
 [3 7 5]
 [3 4 7]
 [2 8 4]]
[[1 0 6 3 4 7]
 [3 7 5 2 8 4]]
------------
[array([[3],
       [2]]), array([[4],
       [8]]), array([[7],
       [4]])]
------------
[array([[3, 4],
       [2, 8]]), array([[7],
       [4]])]
------------
[array([[1, 0, 6]]), array([[3, 7, 5]])]
------------
[array([[1],
       [3]]), array([[0],
       [7]]), array([[6],
       [5]])]
